services:
  devcontainer:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces
      - ~/.ssh:/root/.ssh
      - ~/.docker:/root/.docker
      - ~/.gitconfig:/root/.gitconfig
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
