# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

client:
  connect_to:
    host: 192.168.64.77
    port: 1234
  client:
    host: 192.168.64.66
    port: 1235
server:
  bind:
    host: 192.168.64.77
    port: 1234
  client:
    host: 192.168.64.66
    port: 1235
catnip:
  my_ipv4_addr: 192.168.64.5
  my_link_addr: "52:54:00:90:a4:0f"
  my_interface_name: "enp0s1"
  arp_table:
    "52:54:00:90:a4:0f": 192.168.64.77
    "52:54:00:90:a4:0f": 192.168.64.66
dpdk:
  eal_init: ["", "-c", "0xff", "-n", "4", "-a", "0000:00:01.0","--proc-type=auto"]

# vim: set tabstop=2 shiftwidth=2